# -*- coding: utf-8 -*-
"""NPS_emuca_por_familia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nKTzfD0Qa8zsdeVlacdJvMfCt9f8P3ik

# VALORACIONES DE GOOGLE SHOPPING PARA CÁLCULO DE NPS POR FAMÍLIA

## Librerías
"""

!pip install beautifulsoup4
!pip install google-search-results-serpwow
!pip install google-search-results-serpwow --upgrade

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
from scipy import stats
import pandas as pd 
import multiprocessing
import random

from matplotlib import rc
from sklearn.preprocessing import scale
from sklearn.preprocessing import OneHotEncoder
import timeit
import itertools
import seaborn as sns
from collections import Counter
import operator

import requests
import json
import pandas
import csv
from bs4 import BeautifulSoup
from serpwow.google_search_results import GoogleSearchResults

"""## API Cajones"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca cajones ebay',
           'emuca cajones ferreteria.es',
           'emuca cajones amazon',
           'emuca cajones ferreterias industriales',
           'emuca cajones manommano.es',
           'emuca cajones tuandco.com',
           'emuca cajones masferreteria',
           'emuca cajones valomix',

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_cajones=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<9].sum()
print(nps_value_cajones)

nps_percentage_cajones=nps_value_cajones/df_reviews_emuca['reviews'].sum()
nps_percentage_cajones="{0:.2%}".format(nps_percentage_cajones)
print (nps_percentage_cajones)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_cajones = {'Family_type': ['Cajones'],
        '%NPS': nps_percentage_cajones
        }

NPS_df = pd.DataFrame(NPS_cajones, columns = ['Family_type', '%NPS'])

print (NPS_df)

"""## API Bisagras"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca bisagras ebay',
           'emuca bisagras ferreteria.es',
           'emuca bisagras amazon',
           'emuca bisagras ferreterias industriales',
           'emuca bisagras manommano.es',
           'emuca bisagras tuandco.com',
           'emuca bisagras masferreteria',
           'emuca bisagras valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_bisagras=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_bisagras)

nps_percentage_bisagras=nps_value_bisagras/df_reviews_emuca['reviews'].sum()
nps_percentage_bisagras="{0:.2%}".format(nps_percentage_bisagras)
print (nps_percentage_bisagras)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_bisagras = {'Family_type': 'Bisagras',
        '%NPS': nps_percentage_bisagras
        }

NPS_df = NPS_df.append(NPS_bisagras, ignore_index=True)

print (NPS_df)

"""## API Equipamiento"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca equipamiento ebay',
           'emuca equipamiento ferreteria.es',
           'emuca equipamiento amazon',
           'emuca equipamiento ferreterias industriales',
           'emuca equipamiento manommano.es',
           'emuca equipamiento tuandco.com',
           'emuca equipamiento masferreteria',
           'emuca equipamiento valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_equipamiento=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_equipamiento)

nps_percentage_equipamiento=nps_value_equipamiento/df_reviews_emuca['reviews'].sum()
nps_percentage_equipamiento="{0:.2%}".format(nps_percentage_equipamiento)
print (nps_percentage_equipamiento)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_equipamiento = {'Family_type': 'Equipamiento',
        '%NPS': nps_percentage_equipamiento
        }

NPS_df = NPS_df.append(NPS_equipamiento, ignore_index=True)

print (NPS_df)

"""## API Montaje"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca montaje ebay',
           'emuca montaje ferreteria.es',
           'emuca montaje amazon',
           'emuca montaje ferreterias industriales',
           'emuca montaje manommano.es',
           'emuca montaje tuandco.com',
           'emuca montaje masferreteria',
           'emuca montaje valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_montaje=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_montaje)

nps_percentage_montaje=nps_value_montaje/df_reviews_emuca['reviews'].sum()
nps_percentage_montaje="{0:.2%}".format(nps_percentage_montaje)
print (nps_percentage_montaje)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_montaje = {'Family_type': 'Montaje',
        '%NPS': nps_percentage_montaje
        }

NPS_df = NPS_df.append(NPS_montaje, ignore_index=True)

print (NPS_df)

"""## API Correderos"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca correderos ebay',
           'emuca correderos ferreteria.es',
           'emuca correderos amazon',
           'emuca correderos ferreterias industriales',
           'emuca correderos manommano.es',
           'emuca correderos tuandco.com',
           'emuca correderos masferreteria',
           'emuca correderos valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_correderos=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_correderos)

nps_percentage_correderos=nps_value_correderos/df_reviews_emuca['reviews'].sum()
nps_percentage_correderos="{0:.2%}".format(nps_percentage_correderos)
print (nps_percentage_correderos)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_correderos = {'Family_type': 'Correderos',
        '%NPS': nps_percentage_correderos
        }

NPS_df = NPS_df.append(NPS_correderos, ignore_index=True)

print (NPS_df)

"""## API Armarios"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca armarios ebay',
           'emuca armarios ferreteria.es',
           'emuca armarios amazon',
           'emuca armarios ferreterias industriales',
           'emuca armarios manommano.es',
           'emuca armarios tuandco.com',
           'emuca armarios masferreteria',
           'emuca armarios valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_armarios=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_armarios)

nps_percentage_armarios=nps_value_armarios/df_reviews_emuca['reviews'].sum()
nps_percentage_armarios="{0:.2%}".format(nps_percentage_armarios)
print (nps_percentage_armarios)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_armarios = {'Family_type': 'Armarios',
        '%NPS': nps_percentage_armarios
        }

NPS_df = NPS_df.append(NPS_armarios, ignore_index=True)

print (NPS_df)

"""## API Iluminación"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("7563AA721C454E038A3146CCF1AA949A") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca iluminacion  ebay',
           'emuca iluminacion  ferreteria.es',
           'emuca iluminacion  amazon',
           'emuca iluminacion  ferreterias industriales',
           'emuca iluminacion  manommano.es',
           'emuca iluminacion  tuandco.com',
           'emuca iluminacion  masferreteria',
           'emuca iluminacion  valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_iluminacion=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_iluminacion)

nps_percentage_iluminacion=nps_value_iluminacion/df_reviews_emuca['reviews'].sum()
nps_percentage_iluminacion="{0:.2%}".format(nps_percentage_iluminacion)
print (nps_percentage_iluminacion)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_iluminacion = {'Family_type': 'Iluminación',
        '%NPS': nps_percentage_iluminacion
        }

NPS_df = NPS_df.append(NPS_iluminacion, ignore_index=True)

print (NPS_df)

"""## API Bases"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("9E083A81FB0B470EB5C83270280C9998") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca bases ebay',
           'emuca bases ferreteria.es',
           'emuca bases amazon',
           'emuca bases ferreterias industriales',
           'emuca bases manommano.es',
           'emuca bases tuandco.com',
           'emuca bases masferreteria',
           'emuca bases valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_bases=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_bases)

nps_percentage_bases=nps_value_bases/df_reviews_emuca['reviews'].sum()
nps_percentage_bases="{0:.2%}".format(nps_percentage_bases)
print (nps_percentage_bases)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_bases = {'Family_type': 'Bases',
        '%NPS': nps_percentage_bases
        }

NPS_df = NPS_df.append(NPS_bases, ignore_index=True)

print (NPS_df)

"""## API Tiradores"""

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("9E083A81FB0B470EB5C83270280C9998") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca tiradores ebay',
           'emuca tiradores ferreteria.es',
           'emuca tiradores amazon',
           'emuca tiradores ferreterias industriales',
           'emuca tiradores manommano.es',
           'emuca tiradores tuandco.com',
           'emuca tiradores masferreteria',
           'emuca tiradores valomix'

]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=True).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

df_reviews_emuca["nps"] = 2 * df_reviews_emuca["stars"]
df_reviews_emuca

df_reviews_emuca

df_reviews_emuca[(df_reviews_emuca['nps']<7) | (df_reviews_emuca['nps']>8)]

nps_value_tiradores=df_reviews_emuca['reviews'][df_reviews_emuca['nps']>=9].sum() - df_reviews_emuca['reviews'][df_reviews_emuca['nps']<7].sum()
print(nps_value_tiradores)

nps_percentage_tiradores=nps_value_tiradores/df_reviews_emuca['reviews'].sum()
nps_percentage_tiradores="{0:.2%}".format(nps_percentage_tiradores)
print (nps_percentage_tiradores)

"""Creamos un dataframe donde guardamos el porcentaje de NPS de  cada família"""

NPS_tiradores = {'Family_type': 'Tiradores',
        '%NPS': nps_percentage_tiradores
        }

NPS_df = NPS_df.append(NPS_tiradores, ignore_index=True)

print (NPS_df)

NPS_df_plot=NPS_df

NPS_df_plot['NPS'] = NPS_df_plot['%NPS'].str[:-1].astype(float)

NPS_df_plot

NPS_df_plot = NPS_df_plot.sort_values('NPS')

y_pos

# Name variables
height = NPS_df_plot['NPS']
bars = NPS_df_plot['Family_type']
y_pos = np.arange(len(bars))
 
# Create horizontal bars
plt.barh(y_pos,height)

# Create names on the y-axis

plt.yticks(y_pos, bars)
plt.xlabel('% NPS')
plt.ylabel('Tipo de família')
for index, value in enumerate(height):
    plt.text(value, index, str(value)) 
 
# Show graphic
plt.show()