# -*- coding: utf-8 -*-
"""NPS_emuca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCmC0cUDFUJrbwWDqfqx3Sy3yTvOfZGI

WEB SCRAPPING GOOGLE SHOPPING PARA ANÁLISIS DE SENTIMIENTO
"""

!pip install beautifulsoup4
!pip install google-search-results-serpwow
!pip install google-search-results-serpwow --upgrade

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
from scipy import stats
import pandas as pd 
import multiprocessing
import random

from matplotlib import rc
from sklearn.preprocessing import scale
from sklearn.preprocessing import OneHotEncoder
import timeit
import itertools
import seaborn as sns
from collections import Counter
import operator

import requests
import json
import pandas
import csv
from bs4 import BeautifulSoup
from serpwow.google_search_results import GoogleSearchResults

# This API KEY cames from this site https://app.serpwow.com/playground
serpwow = GoogleSearchResults("2A086E3D970C450C9ED9A369982ADFEA") #This APIKEY is not valid anymore as I already used the 100 free requests.

queries = [
           'emuca cajones ebay',
           'emuca cajones ferreteria.es',
           'emuca cajones amazon',
           'emuca cajones ferreterias industriales',
           'emuca cajones manommano.es',
           'emuca cajones tuandco.com',
           'emuca cajones masferreteria',
           'emuca cajones valomix',

           'emuca bisagras ebay',
           'emuca bisagras ferreteria.es',
           'emuca bisagras amazon',
           'emuca bisagras ferreterias industriales',
           'emuca bisagras manommano.es',
           'emuca bisagras tuandco.com',
           'emuca bisagras masferreteria',
           'emuca bisagras valomix',

           'emuca equipamiento ebay',
           'emuca equipamiento ferreteria.es',
           'emuca equipamiento amazon',
           'emuca equipamiento ferreterias industriales',
           'emuca equipamiento manommano.es',
           'emuca equipamiento tuandco.com',
           'emuca equipamiento masferreteria',
           'emuca equipamiento valomix',   

           'emuca montaje ebay',
           'emuca montaje ferreteria.es',
           'emuca montaje amazon',
           'emuca montaje ferreterias industriales',
           'emuca montaje manommano.es',
           'emuca montaje tuandco.com',
           'emuca montaje masferreteria',
           'emuca montaje valomix', 

           'emuca correderos ebay',
           'emuca correderos ferreteria.es',
           'emuca correderos amazon',
           'emuca correderos ferreterias industriales',
           'emuca correderos manommano.es',
           'emuca correderos tuandco.com',
           'emuca correderos masferreteria',
           'emuca correderos valomix', 

           'emuca armarios ebay',
           'emuca armarios ferreteria.es',
           'emuca armarios amazon',
           'emuca armarios ferreterias industriales',
           'emuca armarios manommano.es',
           'emuca armarios tuandco.com',
           'emuca armarios masferreteria',
           'emuca armarios valomix',  

           'emuca iluminacion  ebay',
           'emuca iluminacion  ferreteria.es',
           'emuca iluminacion  amazon',
           'emuca iluminacion  ferreterias industriales',
           'emuca iluminacion  manommano.es',
           'emuca iluminacion  tuandco.com',
           'emuca iluminacion  masferreteria',
           'emuca iluminacion  valomix', 

           'emuca bases ebay',
           'emuca bases ferreteria.es',
           'emuca bases amazon',
           'emuca bases ferreterias industriales',
           'emuca bases manommano.es',
           'emuca bases tuandco.com',
           'emuca bases masferreteria',
           'emuca bases valomix', 

           'emuca tiradores ebay',
           'emuca tiradores ferreteria.es',
           'emuca tiradores amazon',
           'emuca tiradores ferreterias industriales',
           'emuca tiradores manommano.es',
           'emuca tiradores tuandco.com',
           'emuca tiradores masferreteria',
           'emuca tiradores valomix'
]

results = []

for query in queries:
  params = {
    "q" : query,
    "search_type" : "shopping",
    "time_period" : "custom",
    "time_period_min" : "01/01/2018",
    "time_period_max" : "10/07/2020",
    "sort_by" : "highest_rating"
  }

  result = serpwow.get_json(params)

  if 'shopping_results' in result:
    results += result['shopping_results']

with open('nps_emuca.csv', 'w', encoding='utf-8') as file:
    fields = ['title', 'stars', 'reviews', 'price', 'provider']
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for result in results:
        writer.writerow({
            'title' : result['title'] if 'title' in result else None,
            'stars': result['rating'] if 'rating' in result else None,
            'reviews': result['reviews'] if 'reviews' in result else None, 
            'price': result['price_raw'] if 'price_raw' in result else None, 
            'provider': result['merchant'] if 'merchant' in result else None
            })

from google.colab import drive
drive.mount('/content/drive')

df = pandas.read_csv("/content/nps_emuca.csv")
df

df.nunique()

df.to_csv('/content/drive/My Drive/TFM/03_DATASETS/nps_emuca.csv',sep=';',decimal=',')

df.stars.count()

df.isna().sum()

df_reviews = df[df['stars'].notna()]

df_reviews = df_reviews.reset_index(drop=True)

df_reviews.sort_values(by='stars',ascending=False).head(10)

df_reviews_emuca=df_reviews[df_reviews['title'].str.contains('muca')]
df_reviews_emuca

pd.options.display.max_colwidth

pd.options.display.max_colwidth=500

top_reviews_emuca=df_reviews_emuca[df_reviews_emuca['reviews']>=50].sort_values(by='stars',ascending=False).head(50)

top_reviews_emuca

top_reviews_emuca.title[182]